MvcCoreSessionCubos/Models/Compra.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcCoreSessionCubos.Models
{
    [Table("COMPRA")]
    public class Compra
    {
        [Key]
        [Column("id_compra")]
        public int IdCompra { get; set; }
        [Column("nombre_cubo")]
        public string NombreCubo { get; set; }
        [Column("precio")]
        public int Precio { get; set; }
        [Column("fechapedido")]
        public DateTime fechapedido { get; set; }
    }
}

MvcCoreSessionCubos/Models/Cubo.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcCoreSessionCubos.Models
{
    [Table("CUBOS")]
    public class Cubo
    {
        [Key]
        [Column("id_cubo")]
        public int IdCubo { get; set; }
        [Column("nombre")]
        public string Nombre { get; set; }
        [Column("modelo")]
        public string Modelo { get; set; }
        [Column("marca")]
        public string Marca { get; set; }
        [Column("imagen")]
        public string Imagen { get; set; }
        [Column("precio")]
        public int Precio { get; set; }
    }
}

MvcCoreSessionCubos/Models/ErrorViewModel.cs
namespace MvcCoreSessionCubos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCoreSessionCubos/Controllers/CubosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreSessionCubos.Extensions;
using MvcCoreSessionCubos.Models;
using MvcCoreSessionCubos.Repositories;
using System.Diagnostics;

namespace MvcCoreSessionCubos.Controllers
{
    public class CubosController : Controller
    {
        private RepositoryCubos repo;

        public CubosController(RepositoryCubos repo)
        {
            this.repo = repo;
        }

        public async Task<IActionResult> Index()
        {
            List<Cubo> cubos = await this.repo.GetCubosAsync();
            return View(cubos);
        }

        public IActionResult AnyadirCuboCarrito(int? idcubo)
        {
            if (idcubo != null)
            {
                List<int> carrito;
                if (HttpContext.Session.GetString("CARRITO") == null)
                {
                    carrito = new List<int>();
                }
                else
                {
                    carrito = HttpContext.Session.GetObject<List<int>>("CARRITO");
                }
                carrito.Add(idcubo.Value);
                HttpContext.Session.SetObject("CARRITO", carrito);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Carrito()
        {
            List<int> carrito = HttpContext.Session.GetObject<List<int>>("CARRITO");
            if (carrito != null)
            {
                List<Cubo> cubos = await this.repo.GetCubosSessionAsync(carrito);
                return View(cubos);
            }
            return View();
        }

        public async Task<IActionResult> EliminarCuboCarrito(int? idcubo)
        {
            if (idcubo != null)
            {
                List<int> carrito =
                    HttpContext.Session.GetObject<List<int>>("CARRITO");
                carrito.Remove(idcubo.Value);
                if (carrito.Count() == 0)
                {
                    HttpContext.Session.Remove("CARRITO");
                }
                else
                {
                    HttpContext.Session.SetObject("CARRITO", carrito);
                }
            }
            return RedirectToAction("Carrito");
        }

        public async Task<IActionResult> RealizarCompra()
        {
            List<int> carrito =
                    HttpContext.Session.GetObject<List<int>>("CARRITO");
            List<Compra> compras =
                await this.repo.CreateCompraAsync(carrito);
            HttpContext.Session.Remove("CARRITO");
            return RedirectToAction("Index");
        }
    }
}

MvcCoreSessionCubos/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace MvcCoreSessionCubos.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MvcCoreSessionCubos/Views/Cubos/Carrito.cshtml
@model List<Cubo>

<a asp-controller="Cubos" asp-action="Index"
   class="btn btn-secondary w-25 my-3">
    Volver a Cubos
</a>

@if (Model == null)
{
    <h2 class="text-danger">No hay cubos en tu carrito</h2>
}
else
{
    <h3 class="text-primary mt-3">Cubos en carrito: @Model.Count()</h3>
    <h3 class="text-success mt-2">Precio total: @Model.Sum(c => c.Precio)€</h3>

    <table class="table table-borderless mt-4">
        <thead>
            <tr>
                <th></th>
                <th>Nombre</th>
                <th>Marca</th>
                <th>Modelo</th>
                <th>Precio</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (Cubo cubo in Model)
            {
                <tr>
                    <td><img src="@cubo.Imagen" width="50" height="50" /></td>
                    <td>@cubo.Nombre</td>
                    <td>@cubo.Marca</td>
                    <td>@cubo.Modelo</td>
                    <td>@cubo.Precio</td>
                    <td>
                        <a asp-controller="Cubos" asp-action="EliminarCuboCarrito"
                           asp-route-idcubo="@cubo.IdCubo" class="btn btn-danger w-100">
                            Eliminar del carrito
                        </a>
                    </td>
                </tr>
            }

        </tbody>
    </table>
    <a asp-controller="Cubos" asp-action="RealizarCompra"
       class="btn btn-success w-100 mt-3">
        Realizar compra
    </a>
}

MvcCoreSessionCubos/Views/Cubos/Index.cshtml
@model List<Cubo>

@{
    List<int> carrito = Context.Session.GetObject<List<int>>("CARRITO");
}

<a asp-controller="Cubos" asp-action="Carrito"
   class="btn btn-primary w-100 mt-3">
    Ver tu carrito
</a>

@if (carrito != null)
{
    <h3 class="text-primary mt-3">Cubos en carrito: @carrito.Count()</h3>
}

<table class="table table-borderless mt-3">
    <thead>
        <tr>
            <th></th>
            <th>Nombre</th>
            <th>Marca</th>
            <th>Modelo</th>
            <th>Precio</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (Cubo cubo in Model)
        {
            <tr>
                <td><img src="@cubo.Imagen" width="50" height="50" /></td>
                <td>@cubo.Nombre</td>
                <td>@cubo.Marca</td>
                <td>@cubo.Modelo</td>
                <td>@cubo.Precio</td>
                <td>
                    @if (carrito != null)
                    {
                        @if (!carrito.Contains(cubo.IdCubo))
                        {
                            <a asp-controller="Cubos"
                               asp-action="AnyadirCuboCarrito"
                               asp-route-idcubo="@cubo.IdCubo"
                               class="btn btn-primary w-100">
                                Añadir cubo a carrito
                            </a>
                        }
                        else
                        {
                            <button class="btn btn-secondary w-100">
                                Cubo ya en la cesta
                            </button>
                        }
                    }
                    else
                    {
                        <a asp-controller="Cubos"
                           asp-action="AnyadirCuboCarrito"
                           asp-route-idcubo="@cubo.IdCubo"
                           class="btn btn-primary w-100">
                            Añadir cubo a carrito
                        </a>
                    }

                </td>
            </tr>
        }
    </tbody>
</table>

MvcCoreSessionCubos/Views/Home/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

MvcCoreSessionCubos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreSessionCubos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCoreSessionCubos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCoreSessionCubos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-controller="Cubos" asp-action="Index">Cubos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MvcCoreSessionCubos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>